name: Sync to Amazon ECS

env:
  aws_region: eu-west-2
  s3_bucket: exercism-v3-icons

on:
  push:
    branches:
      - main
  schedule:
    - cron: 50 4 * * *
  workflow_dispatch:

jobs:
  deploy:
    name: Upload images to S3
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@261a7de32bda11ba01f4d75c4ed6caf3739e54be

      - name: Upload assets to s3
        run: |
          aws s3 sync images s3://${{ env.s3_bucket }}/images/ --acl public-read --no-progress --cache-control max-age=31536000
